//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLabb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comment
    {
        public System.Guid Id { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<System.Guid> PhotoID { get; set; }
        public Nullable<System.Guid> AlbumID { get; set; }
    
        public virtual tbl_Album tbl_Album { get; set; }
        public virtual tbl_Photo tbl_Photo { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
